language: r
repos:
  CRAN: https://cloud.r-project.org

warnings_are_errors: false
cache:
  packages: true


r_packages:
  - covr

before_install: 
  - cd TCpredictionbands

install:
  - R -e 'install.packages("devtools")'

script:
  - R CMD build .
  - R CMD check *tar.gz

after_sucess:
  - R -e 'covr::codecov()'
